//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrawABallGame.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawGameStat
    {
        public System.Guid GameID { get; set; }
        public int RoundIterations { get; set; }
        public double CreditAlotted { get; set; }
        public double WonCredit { get; set; }
        public int TotalBalls { get; set; }
        public int DrawCost { get; set; }
        public double SpentCredit { get; set; }
        public int LeftRounds { get; set; }
        public int WinBonus { get; set; }
        public double RTP { get; set; }
        public string FreeDraw { get; set; }
    }
}
